- name: Install nginx
  yum:
    name: "{{ packages }}"
    state: installed
    update_cache: yes
  vars:
    packages:
      - nginx

- name: Copy nginx configuration in place.(dev)
  template:
    src: nginx.conf.dev.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  when: stage == "dev"

- name: Copy nginx configuration in place.(staging or production)
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  when: stage != "dev"

- name: Ensure nginx is restarted and enabled to start at boot.
  service: name=nginx state=restarted enabled=yes
