- name: Create 'web_user' group
  group: name={{ web_user }}

- name: Allow 'web_user' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%{{ web_user }}'
    line: '%{{ web_user }} ALL=(ALL) NOPASSWD: ALL'

- name: Create 'web_user' user
  user:
    name: "{{ web_user }}"
    group: "{{ web_user }}"
    groups: wheel
    shell: /bin/bash

- name: Create users
  user:
    name: "{{ item }}"
    group: "{{ web_user }}"
    groups: wheel
    shell: /bin/bash
  with_items: "{{ users }}"

- name: Set authorized key to users
  authorized_key: >
    user={{ item }}
    key=https://github.com/{{ item }}.keys
  with_items: "{{ users }}"

- name: Set authorized key to web_user
  authorized_key: >
    user={{ web_user }}
    key=https://github.com/{{ item }}.keys
  with_items: "{{ users }}"
